apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: myapp
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: abenavente1/gitops-flux-dive:v1.0.0 # {"$imagepolicy": "myapp:myapp"}
          ports:
            - containerPort: 7000
